#!/usr/bin/env bash
# install nginx and set the server to display Holberton School
sudo apt-get update
sudo apt -y install nginx
echo 'Hello World' > /var/www/html/index.nginx-debian.html
sudo service nginx restart