#!/usr/bin/env bash
# install nginx and set the server to display Holberton School
sudo apt-get update
sudo apt -y install nginx
echo 'Holberton School' > /var/www/html/index.nginx-debian.html
rep="server_name _;\nrewrite /redirect_me https://www.google.com/ permanent;\n"
sed -i 's|server_name _;|'"$rep"'|' /etc/nginx/sites-enabled/default
sudo service nginx restart