#!/usr/bin/env bash
# Install and configure load-balancer server.
apt-get install software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.0
apt-get update
apt-get install haproxy=2.0.\*

echo "ENABLED=1" >> /etc/default/haproxy
echo -e '\nfrontend http_frontend\n\tbind *:80\n\tmode http\n\tdefault_backend http_backend\n' >> /etc/haproxy/haproxy.cfg
echo -e 'backend http_backend\n\tbalance roundrobin\n\tserver node1 35.196.1.33:80 check\n\tserver node2 35.243.140.125:80 check\n' >> /etc/haproxy/haproxy.cfg
service haproxy restart