#!/usr/bin/env bash
# Bash script that displays To infinity and beyond indefinitely
echo_trap(){
    echo "I am invincible!!!"
}

trap echo_trap SIGTERM
while true;do echo "To infinity and beyond"; sleep 2; done