#!/usr/bin/env bash
# FizzBuzz exercise.

i="0"

for i in {1..100}
do
    if [ $((i % 3)) -eq 0 ]
    then
        echo -n "Fizz"
        if [ $((i % 5)) -eq 0 ]
        then
           echo "Buzz"
        else
           echo ""
        fi
    elif [ $((i % 5)) -eq 0 ]
    then
        echo "Buzz"
    else
        echo "$i"
    fi
done