#!/usr/bin/env bash
# comment.
chown -R nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/" /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx restart